set(_CATKIN_CURRENT_PACKAGE "bot_sim")
set(bot_sim_VERSION "0.0.0")
set(bot_sim_MAINTAINER "sentry_train_test <sentry_train_test@todo.todo>")
set(bot_sim_PACKAGE_FORMAT "2")
set(bot_sim_BUILD_DEPENDS "message_generation" "angles" "rospy" "std_msgs" "urdf" "xacro" "message_generation" "dynamic_reconfigure" "roscpp" "serial" "actionlib" "actionlib_msgs" "costmap_converter")
set(bot_sim_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "urdf" "xacro" "angles" "roscpp" "serial" "actionlib" "actionlib_msgs" "costmap_converter")
set(bot_sim_BUILDTOOL_DEPENDS "catkin")
set(bot_sim_BUILDTOOL_EXPORT_DEPENDS )
set(bot_sim_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs" "urdf" "xacro" "message_runtime" "dynamic_reconfigure" "angles" "roscpp" "serial" "actionlib" "actionlib_msgs" "costmap_converter")
set(bot_sim_RUN_DEPENDS "message_runtime" "rospy" "std_msgs" "urdf" "xacro" "dynamic_reconfigure" "angles" "roscpp" "serial" "actionlib" "actionlib_msgs" "costmap_converter")
set(bot_sim_TEST_DEPENDS )
set(bot_sim_DOC_DEPENDS )
set(bot_sim_URL_WEBSITE "")
set(bot_sim_URL_BUGTRACKER "")
set(bot_sim_URL_REPOSITORY "")
set(bot_sim_DEPRECATED "")